"""Fixed issue, unique_name constraint in table FeatureGroup causing insertion error. Created relationship between SubscriptionPlan and Features.

Revision ID: 042ca9037f22
Revises: 1bd18a8d6c3a
Create Date: 2025-02-27 12:08:26.368464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042ca9037f22'
down_revision: Union[str, None] = '1bd18a8d6c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
    op.execute('UPDATE features SET subscription_plan_id = 2 WHERE subscription_plan_id IS NULL')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('subscription_plan_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_features_subscription_plan_id'), ['subscription_plan_id'], unique=False)
        batch_op.create_foreign_key(None, 'subscription_plan', ['subscription_plan_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_features_subscription_plan_id'))
        batch_op.drop_column('subscription_plan_id')

    # ### end Alembic commands ###
